language: node_js

install: npm install jshint -g

script: jshint *.js

notifications:
  email:
    recipients:
      - secure: h1GEDEutgLEHdft95f0AsDeIUKBb4FbX0NJNDlIec8f/wXkWpWUjlSTQOnSCFIYzeon1d3kCxGoIM9lBtP/6uM5L71Dtm8EHQTGqqFQ8cszfyJCPRfB+wvnyZvOAMG/V3H/4NECUqOES6DEcrpQTMuz5dDpMGeHnoLK63pttIok=
    on_success: always

